---
- name: "certbot DNS challenge"
  hosts: 127.0.0.1
  connection: local
  gather_facts: no
  vars:
    validation: "{{ lookup('env', 'CERTBOT_VALIDATION') }}"
    domain: "{{ lookup('env', 'CERTBOT_DOMAIN') }}"
  tasks:
    - name: "Add challenge to route53 zone: {{ domain }}"
      route53: 
        state: present
        zone: "{{ domain.split('.')[1:] | join('.') }}"
        record: "_acme-challenge.{{ domain }}"
        type: TXT
        ttl: 60
        value: '"{{ validation }}"'
        wait: yes
        overwrite: true

